CREATE TABLE COUNTRIES
(
    id        bigint generated by default as identity primary key,
    name      VARCHAR(255),
    continent VARCHAR(255)
);

CREATE TABLE HOSTS
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255),
    surname    varchar(255),
    country_id BIGINT REFERENCES COUNTRIES
);

CREATE TABLE BOOKINGS
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255),
    category     VARCHAR(255),
    host_id      BIGINT REFERENCES HOSTS,
    num_of_rooms INTEGER,
    booked       BOOLEAN DEFAULT FALSE
);

CREATE TABLE RESERVATIONS
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE BOOKINGS_RESERVATION_LIST
(
    booking_id          BIGINT REFERENCES BOOKINGS ON UPDATE CASCADE ON DELETE CASCADE,
    reservation_list_id BIGINT REFERENCES RESERVATIONS ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (booking_id, reservation_list_id)
);

CREATE TABLE USERS
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username            VARCHAR(255),
    password            VARCHAR(255),
    name                VARCHAR(255),
    surname             VARCHAR(255),
    user_role           VARCHAR(255),
    reservation_list_id BIGINT REFERENCES RESERVATIONS
);